# Generated by Django 5.2.5 on 2025-08-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Modelo_da_moto',
            new_name='modelo_da_moto',
        ),
        migrations.AlterField(
            model_name='blog',
            name='motor',
            field=models.IntegerField(help_text='Em centímetros cúbicos'),
        ),
    ]
